application: markermaker-148719
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /markerquery/.*
  script: _go_app

- url: /markerqueryraw/.*
  script: _go_app

- url: /process/.*
  script: _go_app
   
- url: /.*
  script: _go_app
  #login: admin
