application: markermaker-148719
version: 1
runtime: go
api_version: go1

handlers:

- url: /markerquery/.*
  script: _go_app

- url: /markerqueryraw/.*
  script: _go_app
    
- url: /populate/
  script: _go_app
  login: optional

- url: /.*
  script: _go_app
  #login: admin
